[package]
org = "ballerina"
name = "uuid"
version = "1.9.1"
authors = ["Ballerina"]
keywords = ["version", "unique"]
repository = "https://github.com/ballerina-platform/module-ballerina-uuid"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true
